require File.expand_path('../ruby_crc', __FILE__)

desc "Print module version"
task :version do
  puts RubyCrc::VERSION
end

desc "Trasmissor"
task :pack do
  tr = RubyCrc::Sender.new
  puts "Instance: #{tr.inspect}"
  tr.load_payloads
  tr.build
  tr.transmit
  puts "Done."
end

desc "Receiver"
task :unpack do
  tr = RubyCrc::Receiver.new
  puts "Instance: #{tr.inspect}"

  puts "Done."
end
